### ISSUE TITLE
Unable to Install OneKit-Pangle/BaseKit as an xcframework

### ISSUE THREAD

**Issue by akio0911** [bytedance/AdsGlobalPackage#1]
I am trying to install the OneKit-Pangle/BaseKit as an xcframework by adding the following line in my Podfile:

```
pod 'OneKit-Pangle/BaseKit', '1.3.11-xc-fix'
```

However, I'm unable to install it.

```
[!] CocoaPods could not find compatible versions for pod "OneKit-Pangle/BaseKit":
  In Podfile:
    OneKit-Pangle/BaseKit (= 1.3.11-xc-fix)

None of your spec sources contain a spec satisfying the dependency: `OneKit-Pangle/BaseKit (= 1.3.11-xc-fix)`.
```

Could you please let me know if there is a solution to install OneKit-Pangle/BaseKit as an xcframework?

**Comment by chenzhuozy** [comment]
you can update sdk version >= 5.1.0.0
