### ISSUE TITLE
Cannot access repository to install the SDK via swift package manager

### ISSUE THREAD

**Issue by keremerkan** [bytedance/AdsGlobalPackage#25]
Xcode cannot access the repository to install Pange SDK. When the repository URL is entered into Xcode, the following error occurs:

<img width="663" alt="Screenshot 2023-08-10 at 10 20 01" src="https://github.com/bytedance/AdsGlobalPackage/assets/1952491/1811e3b4-7f0e-4f27-9268-94a96dbe5d2b">

The repository seems to need credentials.

**Comment by zry-bd** [comment]
I reproduced your bug only when I have two Xcode.app and I add my Github account in my one Xcode via SSH, then I add Pangle SDK Package in another Xcode. You should add your Github account in another Xcode which you want to add Package or just delete your Github account in another Xcode. No Github account is required when you add Pangle Package.

**Comment by keremerkan** [comment]
I don't have any Github account entered to Xcode. I indeed have both Xcode 14.3.1 and Xcode 15 beta installed on my system. I'll try uninstalling the beta and try again though.
