### ISSUE TITLE
[URGENT] Ad SDK clicking its own interstitial ads!

### ISSUE THREAD

**Issue by keremerkan** [bytedance/AdsGlobalPackage#31]
I have tested the SDK both with AdMob In app bidding integration and as standalone. I am currently testing SDK version 5.4.0-release.9

This happens only with live ads. I cannot replicate it with the test ads.

I am adding a video that shows the problem. Please take a look at the video here: https://qrafter.com/pangle.mp4

What happens here is as following:

1. Ad is created and displayed.
2. I click "skip". The delegate records a "click" in <code>func adDidClick(_ ad: PAGAdProtocol)</code> function and displays the App Store page of the app in the ad.
3. Even if I don't tap "skip", after the video finishes, the ad will click itself to show the App Store page of the app in the ad.
4. I have to close that page. Then, I am greeted with the "Endcard" of Pangle. I have to dismiss that too to return to my app.

This is a very serious bug that would compromise the integrity of our publisher accounts and it is a violation of policy.

**Comment by WillieWangWei** [comment]
We would like to further clarify the problem with him. Is it convenient to leave an email address for communication?

**Comment by keremerkan** [comment]
You can contact me via kerem.erkan [at] gmail [dot] com

**Comment by keremerkan** [comment]
I have not heard from you yet. I installed SDK version 5.4.1 with the same results. The ads still click on themselves and record the click with mediation networks.
