### ISSUE TITLE
Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by SzGajdzica** [bytedance/AdsGlobalPackage#41]
CodeSign /Users/szymon/Library/Developer/Xcode/DerivedData/my-gps-location-ios-gsmfqkbtrqfrtegcttykytuyamkq/Build/Products/Debug-iphonesimulator/my-gps-location-ios.app/Frameworks/PAGAdSDK.framework/Versions/A (in target 'my-gps-location-ios' from project 'my-gps-location-ios')
    cd /Users/szymon/Downloads/my-gps-location-ios-main
    
    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - --timestamp\=none --preserve-metadata\=identifier,entitlements,flags --generate-entitlement-der /Users/szymon/Library/Developer/Xcode/DerivedData/my-gps-location-ios-gsmfqkbtrqfrtegcttykytuyamkq/Build/Products/Debug-iphonesimulator/my-gps-location-ios.app/Frameworks/PAGAdSDK.framework/Versions/A

note: Injecting stub binary into codeless framework (in target 'my-gps-location-ios' from project 'my-gps-location-ios')
/Users/szymon/Library/Developer/Xcode/DerivedData/my-gps-location-ios-gsmfqkbtrqfrtegcttykytuyamkq/Build/Products/Debug-iphonesimulator/my-gps-location-ios.app/Frameworks/PAGAdSDK.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code

**Comment by codeDancer668** [comment]
What version of xcode do you have, suspecting an incompatibility issue from a bug in the latest version of xcode

**Comment by SzGajdzica** [comment]
xcode version 15.3

**Comment by codeDancer668** [comment]
We recommend using xcode 15.2 and below, which can be successfully compiled and run. 
As for the newer versions of xcode 15.3, it does have the above problem.

**Comment by alpha-moisol** [comment]
Will it be fixed anytime soon?

**Comment by alpha-moisol** [comment]
It's a crutial error, we are forced to use Xcode 15.3 starting from May 1, and we cannot use this framework. How long it will take to fix it?

**Comment by zry-bd** [comment]
@alpha-moisol We are seeking resolution，and we will fix it as soon as possible.

**Comment by 1083921307** [comment]
Could you please fix this problem in an urgent manner?   I am waiting for the fix of this problem

**Comment by alpha-moisol** [comment]
Hello, it's been almost a month. When the fix will be released?

**Comment by cheebow** [comment]
When will the revised version be released?
What is the schedule?

**Comment by alpha-moisol** [comment]
@zry-bd @codeDancer668 It's been two months, can we have some information on progress here?

**Comment by zry-bd** [comment]
@alpha-moisol   @cheebow @SzGajdzica Sorry for the delay. We will fix the product within two weeks. Please keep an eye on the version release information.

**Comment by zry-bd** [comment]
@alpha-moisol @cheebow @SzGajdzica We have fixed this error in version 6.1.0-beta.2, please integrate it.

**Comment by DimDL** [comment]
Hi. I tried to integrate:
- version `5.8.0-release.8`: I have the codesign error mentioned above (this ticket).
- version `6.1.0-beta.2` as recommended: Info.plist is invalid, cannot upload to AppStore. I created [this issue](https://github.com/bytedance/AdsGlobalPackage/issues/47)

**Comment by zry-bd** [comment]
@alpha-moisol @cheebow @SzGajdzica @DimDL  We have fixed this codeSign error and [the invalid Info.plist error](https://github.com/bytedance/AdsGlobalPackage/issues/47)  in version 6.1.0-beta.3, please integrate it.

**Comment by hberenger** [comment]
@zry-bd : I just tested `6.1.0-beta.3` and I can confirm it works well in Xcode15.3, thankyou!

**Comment by DimDL** [comment]
@zry-bd I cannot test 6.1.0-beta3 on my side until [Appharbor](https://appharbr.com) starts supporting it, but that is a good step forward, will test when we are unlocked. Thanks !
