### ISSUE TITLE
NSInternalInconsistencyException

### ISSUE THREAD

**Issue by SmartHbdev** [bytedance/AdsGlobalPackage#51]
With latest SPM version of your sdk, mediation with admob. Everything latest version.
No issue some weeks ago. Not sure if related to iOS 18 or something on your side.

Issue is random, maybe depending if it's a banner with picture or if animated.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Set `maskView` (<UIView: 0x105075260; frame = (0 0; 0 0); userInteractionEnabled = NO; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600000347ce0>>) to `nil` before adding it as a subview of <PAG_ZFPlayerControlView: 0x105110460; frame = (0 0; 0 0); backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600000345f80>>'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804b70ec __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008ede8 objc_exception_throw + 72
	2   Foundation                          0x0000000180e73aa8 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000018601651c -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1124
	4   Essence.debug.dylib                 0x0000000107f879b8 -[PAG_ZFPlayerControlView initWithContrlResourceBundle:images:localizedStrings:] + 212
	5   Essence.debug.dylib                 0x0000000107f8de84 -[PAG_ZFPlayerView playerControlView:playerModel:] + 164
	6   Essence.debug.dylib                 0x0000000107f9a0e4 -[PAGLPlayer setupContent] + 424
	7   Essence.debug.dylib                 0x0000000107f9a79c -[PAGLPlayer initWithPlayerItem:] + 88
	8   Essence.debug.dylib                 0x0000000107f9a730 +[PAGLPlayer playerWithPlayerItem:] + 32
	9   Essence.debug.dylib                 0x0000000107ccdcf0 -[PAGNativeExpressVideoView _initPlayer] + 1096
	10  Essence.debug.dylib                 0x0000000107c97424 -[PAGNativeExpressAdView initWithFrame:nativeAd:nativeExpressAdViewSource:] + 400
	11  Essence.debug.dylib                 0x0000000107ccced4 -[PAGNativeExpressVideoView initWithFrame:nativeAd:nativeExpressAdViewSource:] + 464
	12  Essence.debug.dylib                 0x0000000107c9375c -[PAGNativeExpressAdConverter pbu_nativeExpressAdViewWithNativeAd:] + 308
	13  Essence.debug.dylib                 0x0000000107c92d58 -[PAGNativeExpressAdConverter pbu_fetchTemplateDataWithNativeAd:group:syncDownload:] + 88
	14  Essence.debug.dylib                 0x0000000107c9262c __56-[PAGNativeExpressAdConverter convertWithNativeAdArray:]_block_invoke_2.33 + 696
	15  CoreFoundation                      0x000000018041f0b4 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 16
	16  CoreFoundation                      0x00000001804ffbe4 -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 88
	17  Essence.debug.dylib                 0x0000000107c92304 __56-[PAGNativeExpressAdConverter convertWithNativeAdArray:]_block_invoke.32 + 152
	18  libdispatch.dylib                   0x0000000103490ec0 _dispatch_call_block_and_release + 24
	19  libdispatch.dylib                   0x00000001034927b8 _dispatch_client_callout + 16
	20  libdispatch.dylib                   0x00000001034a245c _dispatch_main_queue_drain + 1224
	21  libdispatch.dylib                   0x00000001034a1f84 _dispatch_main_queue_callback_4CF + 40
	22  CoreFoundation                      0x000000018041ae3c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	23  CoreFoundation                      0x0000000180415534 __CFRunLoopRun + 1944
	24  CoreFoundation                      0x0000000180414960 CFRunLoopRunSpecific + 536
	25  GraphicsServices                    0x0000000190183b10 GSEventRunModal + 160
	26  UIKitCore                           0x0000000185aa2b40 -[UIApplication _run] + 796
	27  UIKitCore                           0x0000000185aa6d38 UIApplicationMain + 124
	28  UIKitCore                           0x0000000184e9a184 block_destroy_helper.22 + 9660
	29  Essence.debug.dylib                 0x00000001072ccde4 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
	30  Essence.debug.dylib                 0x00000001072ccd5c $s7Essence11AppDelegateC5$mainyyFZ + 44
	31  Essence.debug.dylib                 0x00000001072ccff0 __debug_main_executable_dylib_entry_point + 28
	32  dyld                                0x00000001031e1410 start_sim + 20
	33  ???                                 0x0000000102f22274 0x0 + 4344390260

**Comment by SzGajdzica** [comment]
Same here, pelase fix

**Comment by hberenger** [comment]
Same here ; we noticed a huge spike of this crash on September 27th and 28th, then nothing.
Is the crashed caused by some specific ads? Has it been somehow fixed server side?

**Comment by SzGajdzica** [comment]
For now i removed the Pangle library, waiting for some information

**Comment by zry-bd** [comment]
@SmartHbdev @SzGajdzica @hberenger 
We have released version 6.2.0-release.9 and you can update SDK to fix it.
